services:
  # --- 1. The Knowledge Graph ---

  # --- 2. The Vector Brain ---
  qdrant:
    image: qdrant/qdrant:v1.13.4
    container_name: vekku-qdrant
    hostname: vekku-qdrant
    ports:
      - "6333:6333" # REST API
      - "6334:6334" # gRPC API
    volumes:
      - ./vekku_data/qdrant/storage:/qdrant/storage
    networks:
      - vekku-net
    restart: unless-stopped

# --- 3. Isolated Network ---
networks:
  vekku-net:
    driver: bridge
    name: vekku-network
